name: tencent-cdn
on: 
  push:
    branches:
      - main
jobs:
  fresh-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for GitHub Pages deployed
        run: sleep 60
      - uses: TencentCloud/cli-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          region: ${{ secrets.TENCENT_PRODUCT_REGION }}
          output_format: json
          commands: cdn PurgePathCache --Paths='["https://hdgcs.com/"]' --FlushType='flush'
